name: Allure Integration

on: [push]

env:
  EMAIL_1: ${{ vars.EMAIL_1 }}
  EMAIL_2: ${{ vars.EMAIL_2 }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        email: [ "EMAIL_1", "EMAIL_2" ]  # Use environment variables as email addresses
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run with Cucumber
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          command: npm run run-smoke-get-allure-report
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
      - name: Send email with artifact
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}
          subject: "Cucumber HTML Report"
          to: ${{ env[matrix.email] }}
          body: |
            Your webpage daily test report is ready.
            
            You can also view the report online: [View Report](https://mkefem.github.io/QA_BDD_Cypress/${{ github.run_number }}/)
            
            Thank you!
          content_type: text/plain
        env:
          CI: 1
          CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
          npm_config_cache: /home/runner/.npm
          TERM: xterm
