name: API Test Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "30 05 * * *" 

jobs:
  Cypress-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test in cypress and generate Multile Cucumber Html Report
        uses: cypress-io/github-action@v6
        with:
          command: npm run TestWithReportGeneration
          browser: chrome

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: artifact
          path: cypress/reports/Results
          retention-days: 2
          # Available Options:
          #   warn: Output a warning but do not fail the action
          #   error: Fail the action with an error message
          #   ignore: Do not output any warnings or errors, the action does not fail
          #   if-no-files-found: 2
