name: API Test Report

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "30 05 * * *"

env:
  EMAIL_1: ${{ vars.EMAIL_1 }}
  EMAIL_2: ${{ vars.EMAIL_2 }}

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install puppeteer

      - name: Run Test in Cypress and generate Cucumber HTML Report
        uses: cypress-io/github-action@v6
        with:
          command: npm run TestWithReportGeneration
          browser: chrome

      - name: Generate PDF Report
        run: |
          node -e "const puppeteer = require('puppeteer'); async function run() { const browser = await puppeteer.launch(); const page = await browser.newPage(); await page.goto('http://localhost:8080/_sql?error_trace', { waitUntil: 'networkidle0' }); await page.pdf({ path: 'cypress/reports/Results/report.pdf', format: 'A4' }); await browser.close(); } run();"

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF_Report
          path: cypress/reports/Results/report.pdf

  Send-Email:
    needs: Cypress-Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        email: ["EMAIL_1", "EMAIL_2"]  # Use environment variables as email addresses
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: HTML_Report_as_PDF
          path: cypress/reports/Results/report.pdf

      - name: Send email with artifact
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}
          subject: "Cucumber HTML Report"
          to: ${{ env[matrix.email] }}
          body: "Please find the attached Cucumber HTML Report."
          attachments: cypress/reports/Results/report.pdf 
          content_type: text/plain
        env:
          CI: 1
          CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
          npm_config_cache: /home/runner/.npm
          TERM: xterm
