name: Daily full Test Report

on:
  push:
    branches: ["master"]

  schedule:
    - cron: "30 05 * * *"

env:
  EMAIL_1: ${{ vars.EMAIL_1 }}
  EMAIL_2: ${{ vars.EMAIL_2 }}

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test in Cypress and generate Cucumber HTML Report
        uses: cypress-io/github-action@v6
        with:
          command: npm run run-smoke-get-mocha-report
          browser: chrome

      - name: Copy test execution videos and images
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: Github Actions
          user_name: ${{ vars.user_name }}
          user_email: ${{ vars.user_email }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: |
            output.html
            cypress/videos/*.mp4
          expire-in: 1d

  Send-Email:
    needs: Cypress-Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        email: ["EMAIL_1", "EMAIL_2"]  # Use environment variables as email addresses
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Report
          path: .

      - name: Send email with artifact
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}
          subject: "Cucumber HTML Report"
          to: ${{ env[matrix.email] }}
          body: "Please find the attached Cucumber HTML Report."
          attachments: output.html, cypress/videos/weathershopper.feature.mp4
          content_type: text/plain
        env:
          CI: 1
          CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
          npm_config_cache: /home/runner/.npm
          TERM: xterm
